applications/venta/urls.py
#
from django.urls import path
from . import views

app_name = "venta_app"

urlpatterns = [
    path('buscar-cliente/', views.BuscarClienteView.as_view(), name='buscar-cliente'),
    path('venta/index/', views.AddCarView.as_view(), name='venta-index'),
    path('venta/carshop/update/<pk>/', views.CarShopUpdateView.as_view(), name='carshop-update'),
    path('venta/carshop/delete/<pk>/', views.CarShopDeleteView.as_view(), name='carshop-delete'),
    path('venta/carshop/delete-all/', views.CarShopDeleteAll.as_view(), name='carshop-delete_all'),
    path('venta/simple/', views.ProcesoVentaSimpleView.as_view(), name='venta-simple'),
    path('venta/voucher/', views.ProcesoVentaVoucherView.as_view(), name='venta-voucher'),
    path('venta/voucher-pdf/<pk>/', views.VentaVoucherPdf.as_view(), name='venta-voucher_pdf'),
    path('venta/ultimas-ventas/', views.SaleListView.as_view(), name='venta-list'),
    path('venta/delete/<pk>/', views.SaleDeleteView.as_view(), name='venta-delete'),
]

market/urls.py
"""
Proyecto de Market
"""
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.home.urls')),
    # caja app
    re_path('', include('applications.caja.urls')),
    # cliente app
    re_path('', include('applications.cliente.urls')),
    # compra app
    re_path('', include('applications.compra.urls')),
    # inventario app
    # re_path('', include('applications.inventario.urls')),
    # producto app
    re_path('', include('applications.producto.urls')),
    # proveedor app
    re_path('', include('applications.proveedor.urls')),
    # users app
    re_path('', include('applications.users.urls')),
    # venta app
    re_path('', include('applications.venta.urls')),
]

applications/venta/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import pre_delete, post_save
#
from model_utils.models import TimeStampedModel
# from django.utils.translation import gettext_lazy as _

# local apps
from applications.producto.models import Producto
from applications.cliente.models import Cliente

#
from .managers import SaleManager, SaleDetailManager, CarShopManager
from .signals import update_stok_ventas_producto


class Sale(TimeStampedModel):
    """Modelo que representa a una Venta Global"""

    # tipo recibo constantes
    NOTAVENTA = '0'
    BOLETA = '1'
    FACTURA = '2'
    SIN_COMPROBANTE = '3'
    # tipo pago constantes
    EFECTIVO = '1'
    VISA = '2'
    MASTERCARD = '3'
    AMERICANEXPRESS = '4'
    DINERSCLUB = '5'
    CHEQUE = '6'
    TRANSFERENCIA = '7'
    YAPE = '8'
    NIUBIZ = '9'
    IZIPAY = '10'
    VENDEMAS = '11'
    PLIN = '12'
    # condicion de pago constantes
    CONTADO = '1'
    CREDITO = '2'
    #
    TIPO_INVOCE_CHOICES = [
        (NOTAVENTA, 'Nota de Venta'),
        (BOLETA, 'Boleta Electrónica'),
        (FACTURA, 'Factura Electrónica'),
        (SIN_COMPROBANTE, 'Sin Comprobante'),
    ]

    TIPO_PAYMENT_CHOICES = [
        (EFECTIVO, 'Efectivo'),
        (VISA, 'VISA'),
        (MASTERCARD, 'MasterCard'),
        (AMERICANEXPRESS, 'American Express'),
        (DINERSCLUB, 'Diners Club'),
        (CHEQUE, 'Cheque'),
        (TRANSFERENCIA, 'Depósito o Transferencia'),
        (YAPE, 'Yape'),
        (NIUBIZ, 'Niubiz'),
        (IZIPAY, 'Izipay'),
        (VENDEMAS, 'Vendemas'),
        (PLIN, 'Plin'),
    ]
    CONDICION_PAGO_CHOICES = [
        (CONTADO, 'Contado'),
        (CREDITO, 'Crédito'),
    ]
    

    cliente = models.ForeignKey(Cliente, related_name="ventas", on_delete=models.CASCADE)
    type_invoce = models.CharField('TIPO', max_length=2, choices=TIPO_INVOCE_CHOICES)
    serie = models.CharField('Serie', max_length=4)
    correlativo = models.CharField('Correlativo', max_length=12)
    type_payment = models.CharField('TIPO PAGO', max_length=2, choices=TIPO_PAYMENT_CHOICES)
    condicion_pago = models.CharField('Estado de Pago', max_length=1, choices=CONDICION_PAGO_CHOICES)
    date_sale = models.DateTimeField('Fecha de Venta',)
    count = models.PositiveIntegerField('Cantidad de Productos')
    subtotal = models.DecimalField('Subtotal', max_digits=10, decimal_places=2)
    igv = models.DecimalField('IGV', max_digits=10, decimal_places=2)
    total = models.DecimalField('Total', max_digits=10, decimal_places=2)
    amount = models.DecimalField('Monto', max_digits=10, decimal_places=2)
    close = models.BooleanField('Venta cerrada', default=False)
    anulado = models.BooleanField('Venta Anulada', default=False,)
    estado = models.BooleanField('Estado', default=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='cajero', related_name="user_venta",)

    objects = SaleManager()

    class Meta:
        verbose_name = 'Venta'
        verbose_name_plural = 'ventas'

    def __str__(self):
        return 'Nº [' + str(self.id) + '] - ' + str(self.date_sale)



class SaleDetail(TimeStampedModel):
    """Modelo que representa a una venta en detalle"""

    product = models.ForeignKey(Producto, on_delete=models.CASCADE, verbose_name='producto', related_name='product_sale')
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE, verbose_name='Codigo de Venta', related_name='detail_sale')
    count = models.PositiveIntegerField('Cantidad')
    unit_price = models.DecimalField('Valor Unitario', max_digits=10, decimal_places=2)
    sale_price = models.DecimalField('Precio Venta', max_digits=10, decimal_places=2)
    tax = models.DecimalField('Impuesto', max_digits=5, decimal_places=2)
    profit = models.DecimalField('Ganancia', max_digits=7, decimal_places=2, default=0) # ganancia de cada venta
    anulado = models.BooleanField(default=False)
    #

    objects = SaleDetailManager()

    class Meta:
        verbose_name = 'Producto Vendido'
        verbose_name_plural = 'Productos vendidos'

    def __str__(self):
        return str(self.sale.id) + ' - ' + str(self.product.name)
    
    # # Añadido para calcular la ganacia en funcion al promedio de costo del producto
    # def save(self, *args, **kwargs):
    #     super().save(*args, **kwargs)
    #     self.calculate_profit()

    # def calculate_profit(self):
    #     producto = self.product
    #     self.profit = (self.sale_price - producto.average_cost) * self.count
    #     self.save()
    # # Fin de añadido


class CarShop(TimeStampedModel):
    """Modelo que representa a un carrito de compras"""
    barcode = models.CharField(max_length=13, unique=True)
    product = models.ForeignKey(Producto, on_delete=models.CASCADE, verbose_name='producto', related_name='product_car_venta')
    count = models.PositiveIntegerField('Cantidad')
    unit_price = models.DecimalField('Precio Unitario', max_digits=7, decimal_places=2)
    sale_price = models.DecimalField('Precio Venta', max_digits=7, decimal_places=2)
    
    objects = CarShopManager()

    class Meta:
        verbose_name = 'Carrito de compras'
        verbose_name_plural = 'Carrito de compras'
        ordering = ['-created']

    def __str__(self):
        return str(self.product.name)


# signals for venta
post_save.connect(update_stok_ventas_producto, sender=SaleDetail)

applications/venta/views.py
# django
# from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse_lazy, reverse
from django.views.generic import (View, UpdateView, DeleteView, ListView )
from django.views.generic.edit import (FormView)
from django.http import JsonResponse
from django.utils import timezone
# local
from applications.producto.models import Producto
from applications.cliente.models import Cliente
from applications.utils import render_to_pdf
from applications.users.mixins import VentasPermisoMixin
#
from .models import Sale, SaleDetail, CarShop
from .forms import VentaForm, VentaVoucherForm, ComprobanteForm
from .functions import procesar_venta

class AddCarView(VentasPermisoMixin, FormView):
    template_name = 'venta/index.html'
    form_class = VentaForm
    success_url = '.'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["productos"] = CarShop.objects.all()
        context["total_cobrar"] = CarShop.objects.total_cobrar()
        # formulario para venta con voucher
        context['form_comprobante'] = ComprobanteForm
        return context
    
    def form_valid(self, form):
        '''
        Dentro de aqui se pueden recuperar los datos enviados
        a traves del metodo POST
        '''
        barcode = form.cleaned_data['barcode']
        count = form.cleaned_data['count']
        unit_price = form.cleaned_data['unit_price']
        sale_price = form.cleaned_data['sale_price']
        product = Producto.objects.get(barcode=barcode)
        
        obj, created = CarShop.objects.get_or_create(
            barcode=barcode,
            defaults={
                'product': product,
                'count': count,
                'unit_price': unit_price,
                'sale_price': sale_price,
            }
        )
        #
        if not created:
            obj.count = obj.count + count
            obj.save()
        return super(AddCarView, self).form_valid(form)
    
class CarShopUpdateView(VentasPermisoMixin, View):
    """ quita en 1 la cantidad en un carshop """
    def post(self, request, *args, **kwargs):
        car = CarShop.objects.get(id=self.kwargs['pk'])
        action = request.POST.get('action')
        
        if action == 'decrease':
            if car.count > 1:
                car.count -= 1
                car.sale_price = car.unit_price * car.count
                car.save()
            else:
                car.delete()
        elif action == 'increase':
            car.count += 1
            car.sale_price = car.unit_price * car.count
            car.save()
        #
        return HttpResponseRedirect(
            reverse(
                'venta_app:venta-index'
            )
        )

class CarShopDeleteView(VentasPermisoMixin, DeleteView):
    model = CarShop
    success_url = reverse_lazy('venta_app:venta-index')

class CarShopDeleteAll(VentasPermisoMixin, View):
    
    def post(self, request, *args, **kwargs):
        #
        CarShop.objects.all().delete()
        #
        return HttpResponseRedirect(
            reverse(
                'venta_app:venta-index'
            )
        )
        
class BuscarClienteView(View):
    def get(self, request, *args, **kwargs):
        numero_documento = request.GET.get('numero_documento', None)
        if numero_documento:
            try:
                cliente = Cliente.objects.get(numero_documento=numero_documento)
                data = {
                    'id': cliente.id,
                    'nombre': cliente.nombre,
                }
            except Cliente.DoesNotExist:
                data = {
                    'error': 'Cliente no encontrado'
                }
        else:
            data = {
                'error': 'Número de documento no proporcionado'
            }
        return JsonResponse(data)

class ProcesoVentaSimpleView(VentasPermisoMixin, View):
    """ Procesa una venta simple """

    def post(self, request, *args, **kwargs):
        #
        procesar_venta(
            self=self,
            type_invoce=Sale.SIN_COMPROBANTE,
            type_payment=Sale.CASH,
            user=self.request.user,
        )
        #
        return HttpResponseRedirect(
            reverse(
                'venta_app:venta-index'
            )
        )

class ProcesoVentaVoucherView(VentasPermisoMixin, FormView):
    def post(self, request, *args, **kwargs):
        form = ComprobanteForm(request.POST)
        if form.is_valid():
            print("Formulario válido. Datos recibidos:")
            cliente_id = form.cleaned_data['cliente_id']
            date_sale = form.cleaned_data['date_sale']
            type_invoce = form.cleaned_data['type_invoce']
            type_payment = form.cleaned_data['type_payment']
            
            venta = procesar_venta(
                self=self,
                cliente_id=cliente_id,
                date_sale=date_sale,
                type_invoce=type_invoce,
                type_payment=type_payment,
                condicion_pago=Sale.CONTADO,
                user=self.request.user,
            )
            if venta:
                print("Venta procesada:", venta.id)
                return HttpResponseRedirect(
                    reverse(
                        'venta_app:venta-voucher_pdf',
                        kwargs={'pk': venta.pk },
                    )
                )
            else:
                print("Error: No se pudo procesar la venta.")
                return HttpResponseRedirect(
                    reverse(
                        'venta_app:venta-index'
                    )
                )
        else:
            print("Formulario inválido. Errores:")
            print(form.errors)
            return HttpResponseRedirect(
                reverse(
                    'venta_app:venta-index'
                )
            )
    
    # Comentado para poder probar otro metodo
    # form_class = ComprobanteForm
    # success_url = '.'
    # template_name = 'venta/voucher_form.html'
    
    # def form_valid(self, form):
    #     proveedor_id = form.cleaned_data['proveedor_id']
    #     date_sale = form.cleaned_data['date_sale']
    #     date_sale = timezone.make_aware(date_sale)
    #     type_payment = form.cleaned_data['type_payment']
    #     type_invoce = form.cleaned_data['type_invoce']
    #     #
    #     venta = procesar_venta(
    #         self=self,
    #         proveedor_id=proveedor_id,
    #         date_sale=date_sale,
    #         serie_comprobante='F001',
    #         numero_comprobante='0001',
    #         type_invoce=type_invoce,
    #         condicion_pago=Sale.CONTADO,
    #         type_payment=type_payment,
    #         user=self.request.user,
    #     )
    #     #
    #     if venta: 
    #         return HttpResponseRedirect(
    #             reverse(
    #                 'venta_app:venta-voucher_pdf',
    #                 kwargs={'pk': venta.pk },
    #             )
    #         )
    #     else:
    #         return HttpResponseRedirect(
    #             reverse(
    #                 'venta_app:venta-index'
    #             )
    #         )
                

class VentaVoucherPdf(VentasPermisoMixin, View):
    
    # def get(self, request, *args, **kwargs):
    #     venta = Sale.objects.get(id=self.kwargs['pk'])
    #     data = {
    #         'venta': venta,
    #         'detalle_productos': SaleDetail.objects.filter(sale__id=self.kwargs['pk'])
    #     }
    #     pdf = render_to_pdf('venta/voucher.html', data)
    #     return HttpResponse(pdf, content_type='application/pdf')
    def get(self, request, *args, **kwargs):
        try:
            print("Iniciando generación de PDF")
            venta = Sale.objects.get(id=self.kwargs['pk'])
            print(f"Venta obtenida: {venta}")
            detalle_productos = SaleDetail.objects.filter(sale__id=self.kwargs['pk'])
            print(f"Detalle de productos: {detalle_productos}")
            
            data = {
                'venta': venta,
                'detalle_productos': detalle_productos
            }
            
            pdf = render_to_pdf('venta/voucher.html', data)
            print("PDF generado correctamente")
            
            return HttpResponse(pdf, content_type='application/pdf')
        except Exception as e:
            print(f"Error al generar el PDF: {e}")
            return HttpResponse("Error al generar el PDF", status=500)


class SaleListView(VentasPermisoMixin, ListView):
    template_name = 'venta/ventas.html'
    context_object_name = "ventas" 
    def get_queryset(self):
        return Sale.objects.ventas_no_cerradas()


class SaleDeleteView(VentasPermisoMixin, DeleteView):
    template_name = "venta/delete.html"
    model = Sale
    success_url = reverse_lazy('venta_app:venta-index')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print("Anulando venta:", self.object.id)  # Mensaje de depuración
        self.object.anulado = True
        self.object.save()
        # actualizmos sl stok y ventas
        SaleDetail.objects.restablecer_stok_num_ventas(self.object.id)
        success_url = self.get_success_url()
        return HttpResponseRedirect(success_url)

templates/venta/base_venta.html
{% extends "panel.html" %}

{% load  static %}

{% block css %}
{% endblock css %}

{% block js %}

{% endblock js %}

templates/venta/delete.html
{% extends "venta/base_venta.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x align-center">
  <h5 class="cell" style="margin-bottom: 1em; text-align: center;">¿Desea eliminar esta Venta?</h5>  
  <form class="cell medium-9 grid-x grid-margin-x align-center" 
    action="{% url 'venta_app:venta-delete' sale.id %}" method="POST">
    {% csrf_token %}
    
    <div class="cell medium-7">
        <div class="card cell">
            <div class="card-divider">
              <h3>Monto: {{ sale.amount }}</h3>
            </div>
            <div class="card-section">
              <h4>ID: {{ sale.id }}</h4>
              <p>FECHA: {{ sale.date_sale }}</p>
              <p>CANTIDAD PRODUCTOS: {{ sale.count }}</p>
              <p>TIPO DE COMPROBANTE: {{ sale.get_type_invoce_display }}</p>
              <p>TIPO DE PAGO: {{ sale.get_type_payment_display }}</p>
            </div>
        </div>
    </div>
    
    <div class="cell medium-6">
      <button type="submit" class="alert button">Anular</button>
      <a href="{% url 'venta_app:venta-index' %}" class="primary button clear">Cancelar</a>
    </div>
  </form>
</div>

{% endblock panel-content %}

templates/venta/index.html
{% extends "venta/base_venta.html" %}
{% load  static %}

{% block js %}
<script>
  document.addEventListener('DOMContentLoaded', function() {
      const countInput = document.getElementById('count');
      const unitPriceInput = document.getElementById('unit_price');
      const salePriceInput = document.getElementById('sale_price');
      let timeout = null;

      function calculatePrices(changedField) {
          const count = parseFloat(countInput.value) || 0;
          const unitPrice = parseFloat(unitPriceInput.value) || 0;
          const salePrice = parseFloat(salePriceInput.value) || 0;

          if (count > 0) {
              if (changedField === 'unit_price' && unitPrice > 0) {
                  salePriceInput.value = (count * unitPrice).toFixed(2);
              } else if (changedField === 'sale_price' && salePrice > 0) {
                  unitPriceInput.value = (salePrice / count).toFixed(2);
              }
          }
      }

      function delayedCalculatePrices(event) {
          clearTimeout(timeout);
          const changedField = event.target.id;
          timeout = setTimeout(() => calculatePrices(changedField), 500); // 500ms delay
      }

      countInput.addEventListener('input', delayedCalculatePrices);
      unitPriceInput.addEventListener('input', delayedCalculatePrices);
      salePriceInput.addEventListener('input', delayedCalculatePrices);
  });

  document.addEventListener('DOMContentLoaded', function() {
      const modal = document.getElementById('registrarVentaModal');
      if (modal) {

        const numeroDocumentoInput = modal.querySelector('input[name="numero_documento"]');
        const nombreClienteInput = modal.querySelector('input[name="nombre_cliente"]');
        const clienteIdInput = modal.querySelector('input[name="cliente_id"]');
        const form = modal.querySelector('form');

        // Función para buscar el proveedor
        function buscarCliente() {
            const numeroDocumento = numeroDocumentoInput.value;
            if (numeroDocumento) {
                fetch(`/buscar-cliente/?numero_documento=${numeroDocumento}`)
                    .then(response => response.json())
                    .then(data => {
                        if (data.nombre) {
                            nombreClienteInput.value = data.nombre;
                            clienteIdInput.value = data.id;
                            // console.log(data);
                        } else {
                            nombreClienteInput.value = '';
                            clienteIdInput.value = '';
                            alert(data.error);
                        }
                    });
            }
        }

        // Evento para cuando se abre el modal
        $(modal).on('open.zf.reveal', function() {
            numeroDocumentoInput.addEventListener('blur', buscarCliente);
        });

        // Evento para cuando se cierra el modal
        $(modal).on('closed.zf.reveal', function() {
            numeroDocumentoInput.removeEventListener('blur', buscarCliente);
        });

        // Evento para capturar y mostrar los datos del formulario en la consola
        form.addEventListener('submit', function(event) {
            event.preventDefault(); // Evita el envío del formulario
            const formData = new FormData(form);
            for (let [key, value] of formData.entries()) {
                console.log(`${key}: ${value}`);
            }
            form.submit(); // Envía el formulario después de mostrar los datos
        });
      }
  });
</script>
{% endblock js %}

{% block panel-content %}

<div class="grid-x grid-margin-x">
  <div class="cell grid-x grid-margin-x">
    <form class="cell small-7 input-group" method="POST">{% csrf_token %}
      <span class="input-group-label">COD</span>
      {{ form.barcode }}
      {{ form.count }}
      {{ form.unit_price }}
      {{ form.sale_price }}
      <div class="input-group-button">
        <input type="submit" class="button secondary" value="Agregar">
      </div>
    </form>
    <div class="cell small-2">
      <a class="cell hollow button secondary" href="{% url 'venta_app:venta-list' %}">
        <i class="fi-trash"></i>
        <span>Ultimas Ventas</span>
      </a>
    </div>
  </div>

  <div class="grid-x grid-margin-x" style="padding: 1.5em;">
    <!-- contendor de la lista de productos en venta -->
    <div class="cell medium-8">
      <h5 class="cell"> Productos en Venta</h5>
      <table class="hover">
        <thead>
          <th width="200">COD</th>
          <th width="250">Nombres</th>
          <th width="100">Cantidad</th>
          <th width="120">Precio Unit (S/)</th>
          <th width="120">Precio Venta(S/)</th>
          <th>Acciones</th>
          <th></th>
        </thead>
        <tbody>
            {% for producto in productos %}
            <tr>
              <td>{{ producto.barcode }}</td>
              <td>{{ producto.product.name }}</td>
              <td>{{ producto.count }}</td>
              <td>{{ producto.unit_price }}</td>
              <td>{{ producto.sale_price }}</td>
              <td>
                <form action="{% url 'venta_app:carshop-update' producto.id %}" method="POST">{% csrf_token %}
                  <input type="hidden" name="action" value="increase">
                  <button type="submit" class="button primary"><i class="fi-plus"></i></button>
                </form>
                <form action="{% url 'venta_app:carshop-update' producto.id %}" method="POST">{% csrf_token %}
                  <input type="hidden" name="action" value="decrease">
                  <button type="submit" class="button primary"><i class="fi-minus"></i></button>
                </form>
              </td>
              <td>
                <form action="{% url 'venta_app:carshop-delete' producto.id %}" method="POST">{% csrf_token %}
                  <button type="submit" class="button alert"><i class="fi-x"></i></button>
                </form>
              </td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
    </div>

    <!-- contiene los resultados resltantes -->
    <div class="cell medium-4">
      <div class="callout success" style="text-align: center;">
        <h5>Total a Cobrar:</h5>
        <h2> S/ {{ total_cobrar }} </h2>
      </div>
      <br>
      <form class="cell" action="{% url 'venta_app:venta-simple' %}"
        method="POST">{% csrf_token %}
        <button type="submit" class="cell button primery" style="padding: 1.5em;">
          <i class="fi-credit-card"></i>
          <span>Venta Rápida</span>
        </button>
      </form>
      <button data-open="registrarVentaModal" class="cell button success" style="padding: 1.5em;">
        <i class="fi-print"></i>
          <span>Registrar Venta</span>
      </button>

      <form class="cell" action="{% url 'venta_app:carshop-delete_all' %}"
        method="POST">{% csrf_token %}
        <button type="submit" class="cell hollow button alert">
          <i class="fi-trash"></i>
          <span>Limpiar Todo</span>
        </button>
      </form>
    </div>
  </div>
  <!-- modal para el cobrar con comprobante de pago -->
  <div class="reveal" id="registrarVentaModal" data-reveal>
    <h3>Detalle del comprobante de pago</h3>
    <form id="voucherForm" action="{% url 'venta_app:venta-voucher' %}" class="grid-x grid-margin-x"
      method="POST" target="_blank">{% csrf_token %}
      <input type="hidden" name="cliente_id" value="">
      <div class="cell medium-6">
        <label>RUC o DNI:</label>
        <div class="input-group">
          <span class="input-group-label"><i class="fi-credit-card"></i></span>
          {{ form_comprobante.numero_documento }}
        </div>
        {% for error in form.numero_documento.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
        {% endfor %}
      </div>
      <div class="cell medium-6">
        <label>Nombre o Razón Social:</label>
        <div class="input-group">
          <span class="input-group-label"><i class="fi-credit-card"></i></span>
          {{ form_comprobante.nombre_cliente }}
        </div>
        {% for error in form.nombre_proveedor.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
        {% endfor %}
      </div>
      <div class="cell medium-6">
        <label>Fecha de Comprobante:</label>
        <div class="input-group">
          <span class="input-group-label"><i class="fi-credit-card"></i></span>
          {{ form_comprobante.date_sale }}
        </div>
        {% for error in form.date_sale.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
        {% endfor %}
      </div>
      <div class="cell medium-6">
        <label>Tipo de Comprobante:</label>
        <div class="input-group">
          <span class="input-group-label"><i class="fi-credit-card"></i></span>
          {{ form_comprobante.type_invoce }}
        </div>
        {% for error in form.type_invoce.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
        {% endfor %}
      </div>
      <div class="cell medium-6">
        <label>Condición de Pago:</label>
        <div class="input-group">
          <span class="input-group-label"><i class="fi-credit-card"></i></span>
          {{ form_comprobante.condicion_pago }}
        </div>
        {% for error in form.type_payment.errors %}
          <p class="cell" style="color: red;">
            {{ error|escape }}
          </p>
        {% endfor %}
      </div>
      <div class="cell medium-6">
        <label>Fecha de Pago:</label>
        <div class="input-group">
          <span class="input-group-label"><i class="fi-credit-card"></i></span>
          {{ form_comprobante.date_payment }}
        </div>
        {% for error in form.date_sale.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
        {% endfor %}
      </div>
      <div class="cell medium-6">
        <label>Medio de Pago:</label>
        <div class="input-group">
          <span class="input-group-label"><i class="fi-credit-card"></i></span>
          {{ form_comprobante.type_payment }}
        </div>
        {% for error in form.condicion_pago.errors %}
          <p class="cell" style="color: red;">
            {{ error|escape }}
          </p>
        {% endfor %}
      </div>
      <button type="submit" class="cell success button">Pagar</button>
    </form>
  </div>
</div>
{% endblock panel-content %}

templates/venta/ventas.html
{% extends "venta/base_venta.html" %}
{% load  static %}
{% block panel-content %}
<div class="grid-x grid-margin-x">
    <h3 class="cell" style="text-align: center;">Ultimas Ventas Registradas</h3>
    <div class="cell">
        <table>
            <thead>
                <th>Número</th>
                <th>Fecha</th>
                <th>RUC</th>
                <th>Razón Social</th>
                <th>Tipo Comprobante</th>
                <th>Serie - Número</th>
                <th>Monto Total</th>
                <th>Anular</th>
            </thead>
            <tbody>
                {% for venta in ventas %}
                <tr>
                  <td>{{venta.id}}</td>
                  <td>{{venta.date_sale|date:'m/d/Y'}}</td>
                  <td>{{venta.cliente.numero_documento}}</td>
                  <td>{{venta.cliente.nombre}}</td>
                  <td>{{venta.get_type_invoce_display}}</td>
                  <td>{{venta.serie}}-{{venta.correlativo}}</td>
                  <td>{{venta.total}}</td>
                  <td>
                    <a href="#" class="button info"><i class="fi-print"></i></a>
                    <a href="#" class="button warning"><i class="fi-eye"></i></a>
                    <a href="{% url 'venta_app:venta-delete' venta.id %}" class="button alert"><i class="fi-x"></i></a>
                  </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock panel-content %}