applications/producto/urls.py
from django.urls import path
from . import views

app_name = 'producto_app'

urlpatterns = [
    path('producto/lista/', views.ProductoListView.as_view(), name='producto_list'),
    path('producto/agregar/', views.ProductoCreateView.as_view(), name='producto_add'),
    path('producto/editar/<pk>/', views.ProductoUpdateView.as_view(), name='producto_update'),
    path('producto/eliminar/<pk>/', views.ProductoDeleteView.as_view(), name='producto_delete'),
    path('producto/detalle/<pk>/', views.ProductoDetailView.as_view(), name='producto_detail'),
    path('producto/detalle/print/<pk>/', views.ProductoDetailViewPdf.as_view(), name='producto_print_detail'),
    path('producto/reporte/', views.FiltrosProductoListView.as_view(), name='producto_filtros'),
]

market/urls.py
"""
Proyecto de Market
"""
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.home.urls')),
    # caja app
    re_path('', include('applications.caja.urls')),
    # cliente app
    re_path('', include('applications.cliente.urls')),
    # compra app
    re_path('', include('applications.compra.urls')),
    # inventario app
    # re_path('', include('applications.inventario.urls')),
    # producto app
    re_path('', include('applications.producto.urls')),
    # proveedor app
    re_path('', include('applications.proveedor.urls')),
    # users app
    re_path('', include('applications.users.urls')),
    # venta app
    re_path('', include('applications.venta.urls')),
]

applications/producto/models.py
# Django
from django.db import models
# third-paty
from model_utils.models import TimeStampedModel
# from django.utils.translation import gettext_lazy as _
# local
from .managers import ProductoManager
from applications.inventario.models import UnidadMedida
from applications.proveedor.models import Proveedor # estoy importando el modelo Proveedor de la app proveedor


class Categoria(TimeStampedModel):
    '''
        Categoria del producto
    '''
    nombre = models.CharField('Nombre', max_length=50)
    padre = models.ForeignKey('self', related_name="hijos", on_delete=models.CASCADE, null=True, blank=True)
    estado = models.BooleanField('Estado', default=True)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    def __str__(self):
        return self.nombre
    
    
class SubCategoria(TimeStampedModel):
    '''
        SubCategoria del producto
    '''
    nombre = models.CharField('Nombre', max_length=50)
    categoria = models.ForeignKey(Categoria, related_name="subcategorias", on_delete=models.CASCADE)
    estado = models.BooleanField('Estado', default=True)

    class Meta:
        verbose_name = 'SubCategoria'
        verbose_name_plural = 'SubCategorias'

    def __str__(self):
        return self.nombre
    
    
class Marca(TimeStampedModel):
    '''
        Marca del producto
    '''
    nombre = models.CharField('Nombre', max_length=50)
    codigo = models.CharField('Codigo', max_length=30)
    user = models.ForeignKey('users.User', related_name="marcas", on_delete=models.CASCADE)
    estado = models.BooleanField('Estado', default=True)

    class Meta:
        verbose_name = 'Marca'
        verbose_name_plural = 'Marcas'

    def __str__(self):
        return self.nombre
    
# ==== ESTOY COMENTANDO ESTE MODELO PARA PODER IMPORTAR EL MODELO PROVEEDOR DE LA APP PROVEEDOR ====

# class Proveedor(TimeStampedModel):
#     '''
#         Proveedor
#     '''
#     nombre = models.CharField('Nombre', max_length=70)
#     ruc = models.CharField('RUC', max_length=13)
#     direccion = models.CharField('Direccion', max_length=100)
#     telefono = models.CharField('Telefono', max_length=10)
#     email = models.EmailField('Email', max_length=100)
#     estado = models.BooleanField('Estado', default=True)

#     class Meta:
#         verbose_name = 'Proveedor'
#         verbose_name_plural = 'Proveedores'

#     def __str__(self):
#         return self.nombre
    
    
class Producto(TimeStampedModel):
    '''
        Producto
    '''
    # UNIT_CHOICES = ('0','Kilogramos'),('1','Litros'),('2','Unidades')
    name = models.CharField('Nombre', max_length=50)
    barcode = models.CharField('Codigo de Barras', max_length=13, unique=True)
    category = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(SubCategoria, on_delete=models.CASCADE)
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    description = models.TextField('Descripcion', max_length=200)
    unit = models.ForeignKey(UnidadMedida, on_delete=models.CASCADE)
    # provider = models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    # precio = models.DecimalField('Precio', max_digits=10, decimal_places=2)
    average_cost = models.DecimalField('Costo Promedio', max_digits=7, decimal_places=2, default=0) # average_cost o costo promedio
    purchase_price = models.DecimalField('precio compra', max_digits=7, decimal_places=2) # purchase_price
    sale_price = models.DecimalField('precio venta', max_digits=7, decimal_places=2) # sale_price
    num_sale = models.PositiveIntegerField('numero de ventas', default=0) # num_sale
    num_purchase = models.PositiveIntegerField('numero de compras', default=0) # num_purchase
    count = models.PositiveIntegerField('Stock en Almacen', default=0)
    due_date = models.DateField('Fecha de Vencimiento', blank=True, null=True)
    estado = models.BooleanField('Estado', default=True)
    
    objects = ProductoManager()

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'

    def __str__(self):
        return self.name

applications/producto/forms.py
# django
from django import forms
# local
from .models import Producto, Categoria, SubCategoria, Marca
from applications.inventario.models import UnidadMedida


class ProductoForm(forms.ModelForm):
    '''
        Formulario para Producto
    '''
    category = forms.ModelChoiceField(queryset=Categoria.objects.all(), empty_label="Seleccione una categoría")
    subcategory = forms.ModelChoiceField(queryset=SubCategoria.objects.all(), empty_label="Seleccione una subcategoría")
    marca = forms.ModelChoiceField(queryset=Marca.objects.all(), empty_label="Seleccione una Marca")
    unit = forms.ModelChoiceField(queryset=UnidadMedida.objects.all(), empty_label="Seleccionar...")
    class Meta:
        model = Producto
        fields = (
            'name',
            'barcode',
            'category',
            'subcategory',
            'marca',
            'description',
            'unit',
            # 'provider',
            'purchase_price',
            'sale_price',
            'count',
            'due_date',
            'estado',
        )
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'placeholder': 'Nombre del producto',
                    'class': 'input-group-field',
                    'autocomplete': 'off',
                }
            ),
            'barcode': forms.TextInput(
                attrs={
                    'placeholder': 'Codigo de barras',
                    'class': 'input-group-field',
                }
            ),
            'category': forms.Select(
                attrs={
                    'class': 'input-group-field',
                }
            ),
            'subcategory': forms.Select(
                attrs={
                    'class': 'input-group-field',
                }
            ),
            'marca': forms.Select(
                attrs={
                    'class': 'input-group-field',
                }
            ),
            'description': forms.Textarea(
                attrs={
                    'placeholder': 'Descripcion del producto',
                    'rows': 3,
                    'class': 'input-group-field',
                }
            ),
            'unit': forms.Select(
                attrs={
                    'class': 'input-group-field',
                }
            ),
            'due_date': forms.DateInput(
                format='%Y-%m-%d',
                attrs={
                    'type': 'date',
                    'class': 'form-control',
                }
            ),
            'count': forms.NumberInput(
                attrs={
                    'placeholder': 'Stock del producto',
                    'class': 'input-group-field',
                }
            ),
            'estado': forms.CheckboxInput(
                attrs={
                    'class': 'input-group-field',
                }
            ),
        }
        
    #validations
    def clean_codigo_barras(self):
        '''
            Valida que el codigo de barras sea unico
        '''
        codigo_barras = self.cleaned_data['codigo_barras']
        if len(codigo_barras) < 11:
            raise forms.ValidationError('Ingrese un codigo de barras valido')
        return codigo_barras
    
    def clean_purhcase_price(self):
        '''
            Valida que el precio de compra sea mayor a 0
        '''
        purchase_price = self.cleaned_data['purchase_price']
        if not purchase_price > 0:
            raise forms.ValidationError('Ingrese un precio de compra mayor a cero')
    
    def clean_sale_price(self):
        '''
            Valida que el precio de venta sea mayor a 0
        '''
        sale_price = self.cleaned_data['sale_price']
        purchase_price = self.cleaned_data['purchase_price']
        if not sale_price >= purchase_price:
            raise forms.ValidationError('El precio de venta debe ser mayor o igual al precio de compra')
        return sale_price

applications/producto/views.py
# django
from datetime import datetime
from django.core.exceptions import ValidationError
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    DetailView,
    View
) 
# local
from applications.venta.models import SaleDetail
from applications.users.mixins import AlmacenPermisoMixin
#
from .models import Producto
from .forms import ProductoForm
from applications.utils import render_to_pdf


class ProductoListView(AlmacenPermisoMixin, ListView):
    template_name = "producto/lista.html"
    context_object_name = 'productos'
    
    def get_queryset(self):
        kword = self.request.GET.get("kword", '')
        order = self.request.GET.get("order", '')
        queryset = Producto.objects.buscar_producto(kword, order)
        return queryset
    
class ProductoCreateView(AlmacenPermisoMixin, CreateView):
    template_name = "producto/form_producto.html"
    form_class = ProductoForm
    success_url = reverse_lazy('producto_app:producto_list')
    
    def form_invalid(self, form):
        # Imprimir los errores del formulario en la consola
        print(form.errors)
        return super().form_invalid(form)
    
class ProductoUpdateView(AlmacenPermisoMixin, UpdateView):
    template_name = "producto/form_producto.html"
    model = Producto
    form_class = ProductoForm
    success_url = reverse_lazy('producto_app:producto_list')
    
class ProductoDeleteView(AlmacenPermisoMixin, DeleteView):
    template_name = "producto/delete.html"
    model = Producto
    success_url = reverse_lazy('producto_app:producto_list')
    
class ProductoDetailView(AlmacenPermisoMixin, DetailView):
    template_name = "producto/detail.html"
    model = Producto
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #
        context['ventas_mes'] = SaleDetail.objects.ventas_mes_producto(self.kwargs['pk'])
        return context
    
class ProductoDetailViewPdf(AlmacenPermisoMixin, View):
    
    def get(self, request, *args, **kwargs):
        producto = Producto.objects.get(id=self.kwargs['pk'])
        data = {
            'producto': producto,
            'ventas_mes': SaleDetail.objects.ventas_mes_producto(self.kwargs['pk'])
        }
        pdf = render_to_pdf('producto/detail-print.html', data)
        return HttpResponse(pdf, content_type='application/pdf')
    
class FiltrosProductoListView(AlmacenPermisoMixin, ListView):
    template_name = "producto/filtros.html"
    context_object_name = 'productos'
    
    def get_queryset(self):
        date_start = self.request.GET.get("date_start", '')
        date_end = self.request.GET.get("date_end", '')

        # Validar formato de fecha
        if date_start:
            try:
                datetime.strptime(date_start, '%Y-%m-%d')
            except ValueError:
                raise ValidationError(f"'{date_start}' no tiene un formato de fecha válido. Debe ser YYYY-MM-DD.")
        
        if date_end:
            try:
                datetime.strptime(date_end, '%Y-%m-%d')
            except ValueError:
                raise ValidationError(f"'{date_end}' no tiene un formato de fecha válido. Debe ser YYYY-MM-DD.")

        # Construir el diccionario de filtros
        filtros = {
            'order': self.request.GET.get("order", ''),
            'kword': self.request.GET.get("kword", ''),
            # 'provider': self.request.GET.get("provider", ''),
            'marca': self.request.GET.get("marca", ''),
        }
        
        if date_start:
            filtros['date_start'] = date_start
        if date_end:
            filtros['date_end'] = date_end

        # Pasar el diccionario de filtros al método filtrar
        queryset = Producto.objects.filtrar(**filtros)
        return queryset

templates/producto/base_producto.html
{% extends "panel.html" %}

{% load  static %}

{% block css %}
{% endblock css %}

{% block js %}

{% endblock js %}

templates/producto/delete.html
{% extends "producto/base_producto.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x align-center">
  <h5 class="cell" style="margin-bottom: 1em; text-align: center;">¿Desea eliminar el producto?</h5>  
  <form class="cell medium-9 grid-x grid-margin-x align-center" 
    action="{% url 'producto_app:producto-delete' product.id %}" method="POST">
    {% csrf_token %}
    
    <div class="cell medium-7">
        <div class="card cell">
            <div class="card-divider">
              Quedan: {{ product.count }}
            </div>
            <div class="card-section">
              <h4>{{ product.name }}</h4>
              <p>Proveedor: {{ product.provider }}</p>
              <p>Descripcion: {{ product.description }}</p>
              <p>Codigo: {{ product.barcode }}</p>
            </div>
        </div>
    </div>
    
    <div class="cell medium-6">
      <button type="submit" class="alert button">Eliminar</button>
      <a href="{% url 'producto_app:producto_list' %}" class="primary button clear">Volver</a>
    </div>
  </form>
</div>

{% endblock panel-content %}

templates/producto/detail-print.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <style>
    .table {
      border-collapse: separate;
    }
    .tr {
      border: 2px solid #424242;
      padding: 5px;
    }
  </style>
</head>
<body>
  <h3>{{ producto.name }}</h3>
  <div>
    <table>
      <tbody>
        <tr>
          <td>Codigo de Barras:</td><td>{{ producto.barcode }}</td>
          <td>Proveedor:</td><td>{{ producto.provider }}</td>
        </tr>
        <tr>
          <td>Marca:</td><td>{{ producto.marca }}</td>
          <td>Vencimiento:</td><td>{{ producto.due_date }}</td>
        </tr>
        <tr>
          <td>Unidad de medida:</td><td>{{ producto.unit.nombre }}</td>
          <td>Proveedor:</td><td>{{ producto.provider }}</td>
        </tr>
        <tr>
          <td>Cantidad en Almacen:</td><td>{{ producto.count }}</td>
          <td>Numero de Ventas:</td><td>{{ producto.num_sale }}</td>
        </tr>
        <tr>
          <td>Precio Venta::</td><td>{{ producto.sale_price }}</td>
          <td>Precio Compra:</td><td>{{ producto.purchase_price }}</td>
        </tr>
        <tr>
          <td>Descripcion:</td><td>{{ producto.description }}</td>
        </tr>
      </tbody>
    </table>
  </div>
  <div>
    <h3>Cantidad de ventas ultimos 30 dias</h3>
  </div>
  <table class="table">
    <thead>
        <th>Fecha</th>
        <th>Producto</th>
        <th>Ventas</th>
    </thead>
    <tbody>
        {% for ventas in ventas_mes %}
        <tr class="tr">
            <td>{{ ventas.sale__date_sale__date }}</td>
            <td>{{ ventas.product__name }}</td>
            <td>{{ ventas.cantidad_vendida }}</td>
        </tr>
        {% empty %}
        <p>No hay ventas para este producto</p>
        {% endfor %}
    </tbody>
  </table>
</body>
</html>

templates/producto/detail.html
{% extends "producto/base_producto.html" %}
{% load  static %}{% block panel-content %}
<div class="grid-x grid-margin-x align-center">
  <h5 class="cell" style="margin-bottom: 1em; text-align: center;">Detalle del producto</h5>  
  <div class="cell medium-9 grid-x grid-margin-x align-center">
    <div class="cell medium-7">
        <div class="card cell">
            <div class="card-section">
              <h4>{{ product.name }}</h4>
              <p><span style="font-weight: bold;">Producto:</span> {{ producto.name }}</p>
              <p><span style="font-weight: bold;">Codigo de Barras:</span> {{ producto.barcode }}</p>
              <p><span style="font-weight: bold;">Proveedor:</span> {{ producto.provider }}</p>
              <p><span style="font-weight: bold;">Marca:</span> {{ producto.marca }}</p>
              <p><span style="font-weight: bold;">Vencimiento:</span> {{ producto.due_date }}</p>
              <p><span style="font-weight: bold;">Unidad de medida:</span> {{ producto.get_unit_display }}</p>
              <p><span style="font-weight: bold;">Cantidad en Almacen:</span> {{ producto.count }}</p>
              <p><span style="font-weight: bold;">Precio Compra:</span> {{ producto.purchase_price }}</p>
              <p><span style="font-weight: bold;">Precio Venta:</span> {{ producto.sale_price }}</p>
              <p><span style="font-weight: bold;">Numero de Ventas:</span> {{ producto.num_sale }}</p>
              <p><span style="font-weight: bold;">Descripcion:</span> {{ producto.description }}</p>
            </div>
        </div>
    </div>
    <h4 class="cell">Ventas en los ultimos 30 dias</h4>
    <div class="cell">
        <table class="hover">
            <thead>
                <th>Fecha</th>
                <th>Producto</th>
                <th>Ventas</th>
            </thead>
            <tbody>
                {% for ventas in ventas_mes %}
                <tr>
                    <td>{{ ventas.sale__date_sale__date }}</td>
                    <td>{{ ventas.product__name }}</td>
                    <td>{{ ventas.cantidad_vendida }}</td>
                </tr>
                {% empty %}
                <p style="color: green;">No hay ventas para este producto</p>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="cell medium-6">
      <a target="_blank" href="{% url 'producto_app:producto_print_detail' producto.id %}" class="primary button">Imprimir</a>
    </div>
  </div>
</div>
{% endblock panel-content %}

templates/producto/filtros.html
{% extends "producto/base_producto.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x">
  <form class="cell grid-x grid-margin-x" method="GET">
    <div class="cell input-group">
      <span class="input-group-label">Codigo o Nombre</span>
      <input class="input-group-field" type="text" id="kword" name="kword" 
        value="{{request.GET.kword}}"
        placeholder="Codigo o nombre ..."
        >
    </div>
    <div class="cell grid-x grid-margin-x">
        <p class="cell">Por Fecha de Vencimiento:</p>
        <input type="date" name="date_start" id="date_start" class="cell medium-4">
        <input type="date" name="date_end" id="date_end" class="cell medium-4">
        <p class="cell">Proveedor o Marca:</p>
        <input type="text" name="provide" id="provider" class="cell medium-4" placeholder="Proveedor...">
        <input type="text" name="marca" id="marca" class="cell medium-4" placeholder="Marca...">
        <button class="cell medium-4 button success">Filtrar</button>
    </div>
  </form>

  <div class="cell grid-x grid-margin-x" style="margin-top: 2em;">
    <table class="hover">
      <thead>
        <th>
          {% if request.path == request.get_full_path %}
          <a href="{{request.get_full_path}}?order=barcode"> Código</a>
          {% else %}
          <a href="{{request.get_full_path}}&order=barcode"> Código</a>
          {% endif %}
        </th>
        <th>
          {% if request.path == request.get_full_path %}
          <a href="{{request.get_full_path}}?order=name"> Nombres</a>
          {% else %}
          <a href="{{request.get_full_path}}&order=name"> Nombres</a>
          {% endif %}
        </th>
        <th>Precio Venta</th>
        <th>Precio Compra</th>
        <th>
          {% if request.path == request.get_full_path %}
          <a href="{{request.get_full_path}}?order=stok">Stock</a>
          {% else %}
          <a href="{{request.get_full_path}}&order=stok">Stock</a>
          {% endif %}
        </th>
        <th>
          {% if request.path == request.get_full_path %}
          <a href="{{request.get_full_path}}?order=num">Vendidos</a>
          {% else %}
          <a href="{{request.get_full_path}}&order=num">Vendidos</a>
          {% endif %}
        </th>
        <!-- <th>Vencimiento</th> -->
        <th>Acciones</th>
      </thead>
      <tbody>
        {% for producto in productos %}
          <tr>
            <td>{{producto.barcode}}</td>
            <td>{{producto.name}}</td>
            <td>{{producto.sale_price}}</td>
            <td>{{producto.purchase_price}}</td>
            <td>{{producto.count}}</td>
            <td>{{producto.num_sale}}</td>
            <!-- <td>{{producto.due_date}}</td> -->
            <td>
              <a href="{% url 'producto_app:producto_detail' producto.id %}" class="button warning"><i class="fi-eye"></i></a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock panel-content %}

templates/producto/form_producto.html
{% extends "producto/base_producto.html" %}
{% load  static %}
{% block panel-content %}

<div class="grid-x grid-margin-x align-center">
  <h3 class="cell" style="margin-bottom: 1em; text-align: center;">Datos de Producto</h3>  
  <form class="cell medium-9 grid-x grid-margin-x" method="POST" action="{% url 'producto_app:producto_add' %}">
    {% csrf_token %}
      
    <div class="cell medium-6">
      <label for="id_barcode">Codigo de barras:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-align-justify"></i></span>
        {{ form.barcode }}
      </div>
      {% for error in form.barcode.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
      {% endfor %}
    </div>
    <div class="cell medium-6">
      <label for="id_name">Nombre:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-book"></i></span>
        {{form.name}}
      </div>
    </div>

    <div class="cell medium-6">
      <label for="id_category">Categoría:</label>
      <div class="input-group">
        {{form.category}}
      </div>
    </div>
    <div class="cell medium-6">
      <label for="id_subcategory">Sub Categoría:</label>
      <div class="input-group">
        {{form.subcategory}}
      </div>
    </div>
    <!-- <div class="cell medium-6">
      <label>Proveedor:</label>
      <div class="input-group">
        {{form.provider}}
      </div>
    </div> -->
    <div class="cell medium-6">
      <label for="id_marca">Marca:</label>
      <div class="input-group">
        {{form.marca}}
      </div>
    </div>

    <div class="cell medium-6">
        <label for="id_unit">Unidad de Medida:</label>
        <div class="input-group">
          {{ form.unit }}
        </div>
      </div>
    <div class="cell medium-6">
      <label for="id_due_date">Fecha de Vencimiento:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-calendar"></i></span>
        {{ form.due_date }}
      </div>
    </div>

    <!-- <div class="cell medium-6">
        <label for="id_provider">Proveedor:</label>
        <div class="input-group">
          <span class="input-group-label"><i class="fi-dollar"></i></span>
          {{form.provider}}
        </div>
    </div> -->
    <div class="cell medium-6">
        <label for="id_purchase_price">Precio Compra:</label>
        <div class="input-group">
          <span class="input-group-label"><i class="fi-dollar"></i></span>
          {{form.purchase_price}}
        </div>
        {% for error in form.purchase_price.errors %}
          <p class="cell" style="color: red;">
            {{ error|escape }}
          </p>
        {% endfor %}
    </div>
    <div class="cell medium-6">
        <label for="id_sale_price">Precio Venta:</label>
        <div class="input-group">
          <span class="input-group-label"><i class="fi-dollar"></i></span>
          {{form.sale_price}}
        </div>
        {% for error in form.sale_price.errors %}
          <p class="cell" style="color: red;">
            {{ error|escape }}
          </p>
        {% endfor %}
    </div>

    <div class="cell medium-12">
      <label for="id_count">Cantidad en Almacen:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-list-number"></i></span>
        {{form.count}}
      </div>
    </div>

    <div class="cell medium-12">
        <label for="id_description">Descripcion del producto:</label>
        <div class="input-group">
          {{form.description}}
        </div>
      </div>
    

    <div class="cell medium-6">
      <button type="submit" class="success button" style="width: 200px;">GUARDAR</button>
      {% if form.errors %}
        <div class="errors">
            <p>Errores en el formulario:</p>
            <ul>
                {% for field, errors in form.errors.items %}
                    <li>{{ field }}: {{ errors }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
      {% if product %}
      <a href="{% url 'producto_app:producto_delete' product.id %}" class="alert button clear">ELIMINAR</a>
      {% endif %}
    </div>
  </form>
</div>

{% endblock panel-content %}

templates/producto/lista.html
{% extends "producto/base_producto.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x">
  <div class="cell grid-x grid-margin-x">
    <form class="cell small-9 input-group" method="GET">
      <span class="input-group-label">COD</span>
      <input class="input-group-field" type="text" id="kword" name="kword" placeholder="nombre o codigo...">
      <div class="input-group-button">
        <input type="submit" class="button secondary" value="Buscar">
      </div>
    </form>
    <div class="cell small-3">
      <a href="{% url 'producto_app:producto_add' %}" class="button success">Registrar Nuevo</a>
    </div>
  </div>


  <div class="cell grid-x grid-margin-x">
    <div class="cell small-2">
      <a href="?order=name">
        <span class="label warning">Por Nombre</span>
      </a>
    </div>
    <div class="cell small-2">
      <a href="?order=date">
        <span class="label secondary">Por Fecha</span>
      </a>
    </div>
    <div class="cell small-2">
      <a href="?order=stok">
        <span class="label">Por Stok</span>
      </a>
    </div>
  </div>

  <div class="cell grid-x grid-margin-x" style="margin-top: 2em;">
    <table class="hover">
      <thead>
        <th>COD</th>
        <th>Nombres</th>
        <th>Precio Venta</th>
        <th>Precio Compra</th>
        <th>Stock</th>
        <th>Vendidos</th>
        <th>Acciones</th>
      </thead>
      <tbody>
        {% for producto in productos %}
          <tr>
            <td>{{producto.barcode}}</td>
            <td>{{producto.name}}</td>
            <td>{{producto.sale_price}}</td>
            <td>{{producto.purchase_price}}</td>
            <td>{{producto.count}}</td>
            <td>{{producto.num_sale}}</td>
            <td>
              <a href="{% url 'producto_app:producto_update' producto.id %}" class="button"><i class="fi-pencil"></i></a>
              <a href="{% url 'producto_app:producto_detail' producto.id %}" class="button warning"><i class="fi-eye"></i></a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock panel-content %}