applications/compra/urls.py
# django
from django.urls import path
from . import views

app_name = "compra_app"

urlpatterns = [
    path('buscar-proveedor/', views.BuscarProveedorView.as_view(), name='buscar-proveedor'),
    path('compra/index/', views.AddCarPurchaseView.as_view(), name='compra-index',),
    path('compra/carshop/update/<pk>/', views.CarShopUpdateView.as_view(), name='carshop-update',),
    path('compra/carshop/delete/<pk>/', views.CarShopDeleteView.as_view(), name='carshop-delete',),
    path('compra/carshop/delete-all/', views.CarShopDeleteAll.as_view(), name='carshop-delete_all',),
    path('compra/contado/', views.ProcesoCompraContadoView.as_view(), name='compra-contado',),
    # path('compra/voucher/', views.ProcesoCompraVoucherView.as_view(), name='compra-voucher',),
    # path('compra/voucher-pdf/<pk>/', views.CompraVoucherPdf.as_view(), name='compra-voucher_pdf',),
    path('compra/ultimas-compras/', views.PurchaseListView.as_view(), name='compra-list',),
    path('compra/delete/<pk>/', views.PurchaseDeleteView.as_view(), name='compra-delete',),
]

market/urls.py
"""
Proyecto de Market
"""
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.home.urls')),
    # caja app
    re_path('', include('applications.caja.urls')),
    # cliente app
    re_path('', include('applications.cliente.urls')),
    # compra app
    re_path('', include('applications.compra.urls')),
    # inventario app
    # re_path('', include('applications.inventario.urls')),
    # producto app
    re_path('', include('applications.producto.urls')),
    # proveedor app
    re_path('', include('applications.proveedor.urls')),
    # users app
    re_path('', include('applications.users.urls')),
    # venta app
    re_path('', include('applications.venta.urls')),
]

applications/compra/models.py
from django.db import models
from django.conf import settings
# third-paty
from model_utils.models import TimeStampedModel
from applications.producto.models import Producto
from applications.proveedor.models import Proveedor
from django.db.models.signals import pre_delete, post_save
# local
from .managers import PurchaseManager, PurchaseDetailManager, CarShopManager
from .signals import update_stok_compras_producto

    

class Purchase(TimeStampedModel):
    '''
        Cabecera de la Compra
    '''
    # tipo recibo constantes
    SIN_COMPROBANTE = '00'
    FACTURA = '01'
    BOLETA = '03'
    NOTACREDITO = '07'
    NOTADEBITO = '08'
    # tipo pago constantes
    EFECTIVO = '1'
    VISA = '2'
    MASTERCARD = '3'
    AMERICANEXPRESS = '4'
    DINERSCLUB = '5'
    CHEQUE = '6'
    TRANSFERENCIA = '7'
    YAPE = '8'
    NIUBIZ = '9'
    IZIPAY = '10'
    VENDEMAS = '11'
    PLIN = '12'
    # condicion de pago constantes
    CONTADO = '1'
    CREDITO = '2'
    #
    TIPO_COMPROBANTE_CHOICES = [
        (SIN_COMPROBANTE, 'Sin Comprobante'),
        (FACTURA, 'Factura'),
        (BOLETA, 'Boleta'),
        (NOTACREDITO, 'Nota de Credito'),
        (NOTADEBITO, 'Nota de Debito'),
    ]
    MEDIOS_PAGO_CHOICES = [
        (EFECTIVO, 'Efectivo'),
        (VISA, 'VISA'),
        (MASTERCARD, 'MasterCard'),
        (AMERICANEXPRESS, 'American Express'),
        (DINERSCLUB, 'Diners Club'),
        (CHEQUE, 'Cheque'),
        (TRANSFERENCIA, 'Depósito o Transferencia'),
        (YAPE, 'Yape'),
        (NIUBIZ, 'Niubiz'),
        (IZIPAY, 'Izipay'),
        (VENDEMAS, 'Vendemas'),
        (PLIN, 'Plin'),
    ]
    CONDICION_PAGO_CHOICES = [
        (CONTADO, 'CONTADO'),
        (CREDITO, 'CREDITO'),
    ]
    
    proveedor = models.ForeignKey(Proveedor, related_name="compras", on_delete=models.CASCADE)
    tipo_comprobante = models.CharField('Tipo de Documento', max_length=2, choices=TIPO_COMPROBANTE_CHOICES)
    serie = models.CharField('Serie', max_length=4)
    correlativo = models.CharField('Correlativo', max_length=12)
    medio_pago = models.CharField('Forma de Pago', max_length=2, choices=MEDIOS_PAGO_CHOICES)
    condicion_pago = models.CharField('Estado de Pago', max_length=1, choices=CONDICION_PAGO_CHOICES)
    fecha_compra = models.DateField('Fecha de Compra')
    cantidad = models.PositiveIntegerField('Cantidad de Productos')
    subtotal = models.DecimalField('Subtotal', max_digits=10, decimal_places=2)
    igv = models.DecimalField('IGV', max_digits=10, decimal_places=2)
    total = models.DecimalField('Total', max_digits=10, decimal_places=2)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='cajero', related_name="user_compra",)
    anulado = models.BooleanField('Anulado', default=False)
    estado = models.BooleanField('Estado', default=True)
    # proveedor, tipo_documento, serie, correlativo, forma_pago, estado_pago, fecha_compra, subtotal, igv, total, anulado, estado
    
    objects = PurchaseManager()

    class Meta:
        verbose_name = 'Compra'
        verbose_name_plural = 'Compras'

    def __str__(self):
        return f'Compra {self.id} - {self.proveedor} - {self.tipo_comprobante} - {self.serie}-{self.correlativo}'
    
class PurchaseDetail(TimeStampedModel):
    ''' Detalle de la Compra '''
    compra_cab = models.ForeignKey(Purchase, related_name="detalles", on_delete=models.CASCADE)
    barcode = models.ForeignKey(Producto, related_name="compras", on_delete=models.CASCADE)
    count = models.PositiveIntegerField('Cantidad')
    unit_price = models.DecimalField('Precio Unitario', max_digits=7, decimal_places=2)
    purchase_price = models.DecimalField('Precio', max_digits=7, decimal_places=2)
    tax = models.DecimalField('Impuesto', max_digits=5, decimal_places=2)
    
    objects = PurchaseDetailManager()

    class Meta:
        verbose_name = 'Compra Detalle'
        verbose_name_plural = 'Compras Detalles'

    def __str__(self):
        return self.barcode.nombre
    
    # Añadido para actualizar el promedio de costo del producto
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.update_product_average_cost()

    def update_product_average_cost(self):
        producto = self.product
        total_quantity = producto.count + self.count
        total_cost = (producto.average_cost * producto.count) + (self.purchase_price * self.count)
        producto.average_cost = total_cost / total_quantity
        producto.save()
    # Fin de añadido
    

class CarShop(TimeStampedModel):
    """ Modelo que representa a un carrito de compras """
    barcode = models.CharField(max_length=13, unique=True)
    product = models.ForeignKey(Producto, on_delete=models.CASCADE, verbose_name='producto', related_name='product_car_compra')
    count = models.PositiveIntegerField('Cantidad')
    unit_price = models.DecimalField('Precio Unitario', max_digits=7, decimal_places=2)
    purchase_price = models.DecimalField('Costo', max_digits=7, decimal_places=2)
    
    objects = CarShopManager()

    class Meta:
        verbose_name = 'Carrito de compras'
        verbose_name_plural = 'Carrito de compras'
        ordering = ['-created']

    def __str__(self):
        return str(self.product.name)


# signals for venta
post_save.connect(update_stok_compras_producto, sender=PurchaseDetail)

applications/venta/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import pre_delete, post_save
#
from model_utils.models import TimeStampedModel
# from django.utils.translation import gettext_lazy as _

# local apps
from applications.producto.models import Producto
from applications.cliente.models import Cliente

#
from .managers import SaleManager, SaleDetailManager, CarShopManager
from .signals import update_stok_ventas_producto


class Sale(TimeStampedModel):
    """Modelo que representa a una Venta Global"""

    # tipo recibo constantes
    NOTAVENTA = '0'
    BOLETA = '1'
    FACTURA = '2'
    SIN_COMPROBANTE = '3'
    # tipo pago constantes
    EFECTIVO = '1'
    VISA = '2'
    MASTERCARD = '3'
    AMERICANEXPRESS = '4'
    DINERSCLUB = '5'
    CHEQUE = '6'
    TRANSFERENCIA = '7'
    YAPE = '8'
    NIUBIZ = '9'
    IZIPAY = '10'
    VENDEMAS = '11'
    PLIN = '12'
    # condicion de pago constantes
    CONTADO = '1'
    CREDITO = '2'
    #
    TIPO_INVOCE_CHOICES = [
        (NOTAVENTA, 'Nota de Venta'),
        (BOLETA, 'Boleta Electrónica'),
        (FACTURA, 'Factura Electrónica'),
        (SIN_COMPROBANTE, 'Sin Comprobante'),
    ]

    TIPO_PAYMENT_CHOICES = [
        (EFECTIVO, 'Efectivo'),
        (VISA, 'VISA'),
        (MASTERCARD, 'MasterCard'),
        (AMERICANEXPRESS, 'American Express'),
        (DINERSCLUB, 'Diners Club'),
        (CHEQUE, 'Cheque'),
        (TRANSFERENCIA, 'Depósito o Transferencia'),
        (YAPE, 'Yape'),
        (NIUBIZ, 'Niubiz'),
        (IZIPAY, 'Izipay'),
        (VENDEMAS, 'Vendemas'),
        (PLIN, 'Plin'),
    ]
    CONDICION_PAGO_CHOICES = [
        (CONTADO, 'Contado'),
        (CREDITO, 'Crédito'),
    ]
    

    cliente = models.ForeignKey(Cliente, related_name="ventas", on_delete=models.CASCADE)
    type_invoce = models.CharField('TIPO', max_length=2, choices=TIPO_INVOCE_CHOICES)
    serie = models.CharField('Serie', max_length=4)
    correlativo = models.CharField('Correlativo', max_length=12)
    type_payment = models.CharField('TIPO PAGO', max_length=2, choices=TIPO_PAYMENT_CHOICES)
    condicion_pago = models.CharField('Estado de Pago', max_length=1, choices=CONDICION_PAGO_CHOICES)
    date_sale = models.DateTimeField('Fecha de Venta',)
    count = models.PositiveIntegerField('Cantidad de Productos')
    subtotal = models.DecimalField('Subtotal', max_digits=10, decimal_places=2)
    igv = models.DecimalField('IGV', max_digits=10, decimal_places=2)
    total = models.DecimalField('Total', max_digits=10, decimal_places=2)
    amount = models.DecimalField('Monto', max_digits=10, decimal_places=2)
    close = models.BooleanField('Venta cerrada', default=False)
    anulado = models.BooleanField('Venta Anulada', default=False,)
    estado = models.BooleanField('Estado', default=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='cajero', related_name="user_venta",)

    objects = SaleManager()

    class Meta:
        verbose_name = 'Venta'
        verbose_name_plural = 'ventas'

    def __str__(self):
        return 'Nº [' + str(self.id) + '] - ' + str(self.date_sale)



class SaleDetail(TimeStampedModel):
    """Modelo que representa a una venta en detalle"""

    product = models.ForeignKey(Producto, on_delete=models.CASCADE, verbose_name='producto', related_name='product_sale')
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE, verbose_name='Codigo de Venta', related_name='detail_sale')
    count = models.PositiveIntegerField('Cantidad')
    unit_price = models.DecimalField('Valor Unitario', max_digits=10, decimal_places=2)
    sale_price = models.DecimalField('Precio Venta', max_digits=10, decimal_places=2)
    tax = models.DecimalField('Impuesto', max_digits=5, decimal_places=2)
    profit = models.DecimalField('Ganancia', max_digits=7, decimal_places=2, default=0) # ganancia de cada venta
    anulado = models.BooleanField(default=False)
    #

    objects = SaleDetailManager()

    class Meta:
        verbose_name = 'Producto Vendido'
        verbose_name_plural = 'Productos vendidos'

    def __str__(self):
        return str(self.sale.id) + ' - ' + str(self.product.name)
    
    # # Añadido para calcular la ganacia en funcion al promedio de costo del producto
    # def save(self, *args, **kwargs):
    #     super().save(*args, **kwargs)
    #     self.calculate_profit()

    # def calculate_profit(self):
    #     producto = self.product
    #     self.profit = (self.sale_price - producto.average_cost) * self.count
    #     self.save()
    # # Fin de añadido


class CarShop(TimeStampedModel):
    """Modelo que representa a un carrito de compras"""
    barcode = models.CharField(max_length=13, unique=True)
    product = models.ForeignKey(Producto, on_delete=models.CASCADE, verbose_name='producto', related_name='product_car_venta')
    count = models.PositiveIntegerField('Cantidad')
    unit_price = models.DecimalField('Precio Unitario', max_digits=7, decimal_places=2)
    sale_price = models.DecimalField('Precio Venta', max_digits=7, decimal_places=2)
    
    objects = CarShopManager()

    class Meta:
        verbose_name = 'Carrito de compras'
        verbose_name_plural = 'Carrito de compras'
        ordering = ['-created']

    def __str__(self):
        return str(self.product.name)


# signals for venta
post_save.connect(update_stok_ventas_producto, sender=SaleDetail)

applications/compra/forms.py
from django import forms
from .models import Purchase, PurchaseDetail
#

class ComprobanteForm(forms.ModelForm):
    numero_documento = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'input-group-field',
                'placeholder': 'Ingrese RUC o DNI del proveedor',
            }
        )
    )
    nombre_proveedor = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'input-group-field',
                'readonly': 'readonly',
            }
        )
    )
    proveedor_id = forms.CharField(
        required=False,
        widget=forms.HiddenInput()
    )
    fecha_comprobante = forms.DateField(
        required=True,
        widget=forms.DateInput(
            format='%Y-%m-%d',
            attrs={
                'type': 'date',
                'class': 'input-group-field',
            }
        )
    )
    tipo_comprobante = forms.ChoiceField(
        required=True,
        choices=Purchase.TIPO_COMPROBANTE_CHOICES,
        widget=forms.Select(
            attrs={
                'class': 'input-group-field',
            }
        )
    )
    serie_comprobante = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'input-group-field',
            }
        )
    )
    numero_comprobante = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'input-group-field',
            }
        )
    )
    medio_pago = forms.ChoiceField(
        required=True,
        choices=Purchase.MEDIOS_PAGO_CHOICES,
        widget=forms.Select(
            attrs={
                'class': 'input-group-field',
            }
        )
    )

    class Meta:
        model = Purchase
        fields = ['numero_documento', 'nombre_proveedor', 'proveedor_id', 'fecha_comprobante', 'tipo_comprobante', 'serie_comprobante', 'numero_comprobante', 'medio_pago']
        
   
class CompraForm(forms.ModelForm):
    barcode = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs = {
                'placeholder': 'Codigo de barras',
                'class': 'input-group-field',
            }
        )
    )
    count = forms.IntegerField(
        min_value=1,
        widget=forms.NumberInput(
            attrs = {
                'placeholder': '1',
                'class': 'input-group-field',
            }
        )
    )
    unit_price = forms.DecimalField(
        min_value=0,
        decimal_places=2,
        widget=forms.NumberInput(
            attrs = {
                'placeholder': '0.00',
                'class': 'input-group-field',
            }
        )
    )
    purchase_price = forms.DecimalField(
        min_value=0,
        decimal_places=2,
        widget=forms.NumberInput(
            attrs = {
                'placeholder': '0.00',
                'class': 'input-group-field',
            }
        )
    )
    # condicion_pago = forms.ChoiceField(
    #     required=False,
    #     choices=Purchase.CONDICION_PAGO_CHOICES,
    #     widget=forms.Select(
    #         attrs = {
    #             'class': 'input-group-field',
    #         }
    #     )
    # )
    
    def clean_count(self):
        count = self.cleaned_data['count']
        if count < 1:
            raise forms.ValidationError('Ingrese una cantidad mayor a cero')
        return count
    
    class Meta:
        model = Purchase
        fields = ['barcode', 'count','unit_price', 'purchase_price']
    
class CompraVoucherForm(forms.Form):

    type_payment = forms.ChoiceField(
        required=False,
        choices=Purchase.CONDICION_PAGO_CHOICES,
        widget=forms.Select(
            attrs = {
                'class': 'input-group-field',
            }
        )
    )
    type_invoice = forms.ChoiceField(
        required=False,
        choices=Purchase.TIPO_COMPROBANTE_CHOICES,
        widget=forms.Select(
            attrs = {
                'class': 'input-group-field',
            }
        )
    )

class CompraDetalleForm(forms.ModelForm):
    class Meta:
        model = PurchaseDetail
        fields = '__all__'

templates/compra/index.html
{% extends "compra/base_compra.html" %}
{% load  static %}

{% block js %}
<script>
  document.addEventListener('DOMContentLoaded', function() {
      const modal = document.getElementById('exampleModal1');
      const numeroDocumentoInput = modal.querySelector('input[name="numero_documento"]');
      const nombreProveedorInput = modal.querySelector('input[name="nombre_proveedor"]');
      const proveedorIdInput = modal.querySelector('input[name="proveedor_id"]');
      const form = modal.querySelector('form');

      // Función para buscar el proveedor
      function buscarProveedor() {
          const numeroDocumento = numeroDocumentoInput.value;
          if (numeroDocumento) {
              fetch(`/buscar-proveedor/?numero_documento=${numeroDocumento}`)
                  .then(response => response.json())
                  .then(data => {
                      if (data.nombre) {
                          nombreProveedorInput.value = data.nombre;
                          proveedorIdInput.value = data.id;
                          // console.log(data);
                      } else {
                          nombreProveedorInput.value = '';
                          proveedorIdInput.value = '';
                          alert(data.error);
                      }
                  });
          }
      }

      // Evento para cuando se abre el modal
      $(modal).on('open.zf.reveal', function() {
          numeroDocumentoInput.addEventListener('blur', buscarProveedor);
      });

      // Evento para cuando se cierra el modal
      $(modal).on('closed.zf.reveal', function() {
          numeroDocumentoInput.removeEventListener('blur', buscarProveedor);
      });

      // Evento para capturar y mostrar los datos del formulario en la consola
      form.addEventListener('submit', function(event) {
          event.preventDefault(); // Evita el envío del formulario
          const formData = new FormData(form);
          for (let [key, value] of formData.entries()) {
              console.log(`${key}: ${value}`);
          }
          form.submit(); // Envía el formulario después de mostrar los datos
      });
  });
  document.addEventListener('DOMContentLoaded', function() {
      const countInput = document.getElementById('count');
      const unitPriceInput = document.getElementById('unit_price');
      const purchasePriceInput = document.getElementById('purchase_price');
      let timeout = null;

      function calculatePrices(changedField) {
          const count = parseFloat(countInput.value) || 0;
          const unitPrice = parseFloat(unitPriceInput.value) || 0;
          const purchasePrice = parseFloat(purchasePriceInput.value) || 0;

          if (count > 0) {
              if (changedField === 'unit_price' && unitPrice > 0) {
                  purchasePriceInput.value = (count * unitPrice).toFixed(2);
              } else if (changedField === 'purchase_price' && purchasePrice > 0) {
                  unitPriceInput.value = (purchasePrice / count).toFixed(2);
              }
          }
      }

      function delayedCalculatePrices(event) {
          clearTimeout(timeout);
          const changedField = event.target.id;
          timeout = setTimeout(() => calculatePrices(changedField), 500); // 500ms delay
      }

      countInput.addEventListener('input', delayedCalculatePrices);
      unitPriceInput.addEventListener('input', delayedCalculatePrices);
      purchasePriceInput.addEventListener('input', delayedCalculatePrices);
  });
</script>
{% endblock js %}

{% block panel-content %}

<div class="grid-x grid-margin-x">
  <h3 class="cell"> Nueva Compra</h5>
  <div class="cell grid-x grid-margin-x">
    <form class="cell small-7 input-group" method="POST">{% csrf_token %}
      <span class="input-group-label">Código:</span>
      {{ form.barcode }}
      <input type="number" id="count" name="count" class="input-group-field" placeholder="1" min="1">
      <input type="number" id="unit_price" name="unit_price" class="input-group-field" placeholder="0.00" step="0.01" min="0">
      <input type="number" id="purchase_price" name="purchase_price" class="input-group-field" placeholder="0.00" step="0.01" min="0">
      <div class="input-group-button">
        <input type="submit" class="button secondary" value="Agregar">
      </div>
    </form>
    <div class="cell small-2">
      <a class="cell hollow button secondary" href="{% url 'compra_app:compra-list' %}">
        <i class="fi-trash"></i>
        <span>Ultimas Compras</span>
      </a>
    </div>
  </div>

  <div class="grid-x grid-margin-x" style="padding: 1.5em;">
    <!-- contendor de la lista de productos en venta -->
    <div class="cell medium-8">
      <h5 class="cell"> Productos en Compra</h5>
      <table class="hover">
        <thead>
          <th width="200">COD</th>
          <th width="250">Nombres</th>
          <th width="100">Cantidad</th>
          <th width="120">Precio Unit(S/)</th>
          <th width="120">Precio Compra(S/)</th>
          <th>Acciones</th>
          <th></th>
        </thead>
        <tbody>
            {% for producto in productos %}
            <tr>
              <td>{{ producto.barcode }}</td>
              <td>{{ producto.product.name }}</td>
              <td>{{ producto.count }}</td>
              <td>{{ producto.unit_price }}</td>
              <td>{{ producto.purchase_price }}</td>
              <td>
                <form action="{% url 'compra_app:carshop-update' producto.id %}" method="POST">{% csrf_token %}
                  <input type="hidden" name="action" value="increase">
                  <button type="submit" class="button primary"><i class="fi-plus"></i></button>
                </form>
                <form action="{% url 'compra_app:carshop-update' producto.id %}" method="POST">{% csrf_token %}
                  <input type="hidden" name="action" value="decrease">
                  <button type="submit" class="button primary"><i class="fi-minus"></i></button>
              </form>
              </td>
              <td>
                <form action="{% url 'compra_app:carshop-delete' producto.id %}" method="POST">{% csrf_token %}
                  <button type="submit" class="button alert"><i class="fi-x"></i></button>
                </form>
              </td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
    </div>

    <!-- contiene los resultados resltantes -->
    <div class="cell medium-4">
      <div class="callout success" style="text-align: center;">
        <h5>Total por Pagar:</h5>
        <h2> S/ {{ total_pagar }} </h2>
      </div>
      <br>
      <button data-open="exampleModal1" class="cell button success" style="padding: 1.5em;">
        <i class="fi-print"></i>
          <span>Pagar</span>
      </button>

      <form class="cell" action="{% url 'compra_app:carshop-delete_all' %}" 
        method="POST">{% csrf_token %}
        <button type="submit" class="cell hollow button alert">
          <i class="fi-trash"></i>
          <span>Limpiar Todo</span>
        </button>
      </form>
    </div>
  </div>
  <!-- modal para el cobrar con comprobante de pago -->
  <div class="reveal" id="exampleModal1" data-reveal>
    <h3>Detalle del comprobante de pago</h3>
    <form id="comprobanteForm" action="{% url 'compra_app:compra-contado' %}" class="grid-x grid-margin-x" 
      method="POST" target="_blank">{% csrf_token %}
      <input type="hidden" name="proveedor_id" value="">
      <div class="cell medium-6">
        <label>RUC o DNI:</label>
        <div class="input-group">
          <span class="input-group-label"><i class="fi-credit-card"></i></span>
          {{ form_comprobante.numero_documento }}
        </div>
        {% for error in form.numero_documento.errors %}
          <p class="cell" style="color: red;">
            {{ error|escape }}
          </p>
        {% endfor %}
      </div>
      <div class="cell medium-6">
        <label>Nombre o Razón Social:</label>
        <div class="input-group">
          <span class="input-group-label"><i class="fi-credit-card"></i></span>
          {{ form_comprobante.nombre_proveedor }}
        </div>
        {% for error in form.nombre_proveedor.errors %}
          <p class="cell" style="color: red;">
            {{ error|escape }}
          </p>
        {% endfor %}
      </div>
      <div class="cell medium-6">
        <label>Fecha de Comprobante:</label>
        <div class="input-group">
          <span class="input-group-label"><i class="fi-credit-card"></i></span>
          {{ form_comprobante.fecha_comprobante }}
        </div>
        {% for error in form.fecha_comprobante.errors %}
          <p class="cell" style="color: red;">
            {{ error|escape }}
          </p>
        {% endfor %}
      </div>
      <div class="cell medium-6">
        <label>Tipo de Comprobante:</label>
        <div class="input-group">
          <span class="input-group-label"><i class="fi-credit-card"></i></span>
          {{ form_comprobante.tipo_comprobante }}
        </div>
        {% for error in form.tipo_comprobante.errors %}
          <p class="cell" style="color: red;">
            {{ error|escape }}
          </p>
        {% endfor %}
      </div>
      <div class="cell medium-6">
        <label>Serie:</label>
        <div class="input-group">
          <span class="input-group-label"><i class="fi-credit-card"></i></span>
          {{ form_comprobante.serie_comprobante }}
        </div>
        {% for error in form.serie_comprobante.errors %}
          <p class="cell" style="color: red;">
            {{ error|escape }}
          </p>
        {% endfor %}
      </div>
      <div class="cell medium-6">
        <label>Número:</label>
        <div class="input-group">
          <span class="input-group-label"><i class="fi-credit-card"></i></span>
          {{ form_comprobante.numero_comprobante }}
        </div>
        {% for error in form.numero_comprobante.errors %}
          <p class="cell" style="color: red;">
            {{ error|escape }}
          </p>
        {% endfor %}
      </div>
      <div class="cell medium-6">
        <label>Medio de Pago:</label>
        <div class="input-group">
          <span class="input-group-label"><i class="fi-credit-card"></i></span>
          {{ form_comprobante.medio_pago }}
        </div>
        {% for error in form.medio_pago.errors %}
          <p class="cell" style="color: red;">
            {{ error|escape }}
          </p>
        {% endfor %}
      </div>
      <button type="submit" class="cell success button">Pagar</button>
    </form>
  </div>
</div>
{% endblock panel-content %}

templates/compra/pago.html
{% extends "compra/base_compra.html" %}
{% load  static %}
{% block panel-content %}
<div class="grid-x grid-margin-x">
    <h3 class="cell" style="text-align: center;">Método de Pago</h3>
    <div class="cell">
        <table>
            <thead>
                <th>Número</th>
                <th>Fecha</th>
                <th>Cantidad Productos</th>
                <th>Monto Total</th>
                <th>Anular</th>
            </thead>
            <tbody>
                {% for compra in compras %}
                <tr>
                  <td>{{compra.id}}</td>
                  <td>{{compra.date_sale}}</td>
                  <td>{{compra.count}}</td>
                  <td>{{compra.amount}}</td>
                  <td>
                    <a href="{% url 'compra_app:compra-delete' compra.id %}" class="button alert"><i class="fi-x"></i></a>
                  </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock panel-content %}